#Write a program to enter two integers, two floating numbers and then perform all arithmetic operations on them.

a=int(input("Enter the interger number "))
b=int(input("Enter the second integer number "))
c=float(input("Enter the 3rd float number "))
d=float(input("Enter the 4th float number "))
print("Additon of two integer number is = ",a+b)
print("Addition of two float number is = ",c+d)
print("Subtraction of two integer number is = ",a-b)
print("Subtraction of two float number is = ",c-d)
print("Modulus of two integer number is = ",a%b)
print("Modulus of two flaot number is = ",c%d)
print("Multiplication of two integer number is = ",a*b)
print("Multiplication of two flaot number is = ",c*d)
print("Interger division of two integer number is = ",a//b)
print("Interger division of two float number is = ",c//d)
print("Float division of two integer number is = ",a/b)
print("Float division of two float number is = ",c/d)
print("Exponent of two integer number is = ",a**b)
print("Exponent of two float number is = ",c**d)